[request_definition]
r = sub, obj, act

[policy_definition]
p = rol, subject, act, owner_only

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.sub.rol == p.rol && r.obj.subject == p.subject && r.act == p.act && (p.owner_only == "false" || r.obj.owner_id == r.sub.id)
